export { User } from "./user.model";
export type { IUser } from "./user.model";
export { StudentProfile } from "./student-profile.model";
export type { IStudentProfile } from "./student-profile.model";
export { TeacherProfile } from "./teacher-profile.model";
export type { ITeacherProfile } from "./teacher-profile.model";
export { ParentStudent } from "./parent-student.model";
export type { IParentStudent } from "./parent-student.model";
export { AcademicYear } from "./academic-year.model";
export type { IAcademicYear } from "./academic-year.model";
export { Class } from "./class.model";
export type { IClass } from "./class.model";
export { Subject } from "./subject.model";
export type { ISubject } from "./subject.model";
export { ClassSubject } from "./class-subject.model";
export type { IClassSubject } from "./class-subject.model";
export { Enrollment } from "./enrollment.model";
export type { IEnrollment } from "./enrollment.model";
export { AttendanceRecord } from "./attendance-record.model";
export type { IAttendanceRecord } from "./attendance-record.model";
export { Assignment } from "./assignment.model";
export type { IAssignment } from "./assignment.model";
export { Grade } from "./grade.model";
export type { IGrade } from "./grade.model";
export { LoginAttempt } from "./login-attempt.model";
export type { ILoginAttempt } from "./login-attempt.model";
